### ISSUE TITLE
part 2 feedback

### ISSUE THREAD

**Issue by andreashandel** [anjoru/RUIZ-MADA-project#2]
I can't render your main document, i get this error:

Quitting from lines 202-214 (Manuscript.qmd) 
Error in kable(eee_positive_by_county, "html", col.names = c("County",  : 
  could not find function "%>%"
Calls: .main ... withVisible -> eval_with_user_handlers -> eval -> eval

Can you please fix and make sure everything is reproducible. Let me know once done, then I'll take another look. Thanks.

**Comment by anjoru** [comment]
Hi Dr. Handel, 
Thank you for giving me the opportunity to fix the rendering error. There were some issues with variable names that was causing problems. 
I tested it before I committed the last changes and it rendered without issues a couple of weeks ago, but I seem to have those kinds of issues with my qmd. 

Best, 
Andrew

**Comment by anjoru** [comment]
My apologies if this is a duplicate email since i replied to your comment
on GitHub. I wanted to let you know that i believe i fixed the rendering
issue.

**Comment by andreashandel** [comment]
just tried again, still not working, same error message. you are likely just missing to load dplyr in your manuscript file.

**Comment by anjoru** [comment]
I am so sorry for this. I will try to fix it again but i understand if you
decide not to score it.

**Comment by anjoru** [comment]
Hi Dr. Handel,
I think I fixed it this time. I tried it on a second computer just to make
sure it worked.

Again, thank you for letting me know about the error and giving me the
chance to correct it.

**Comment by andreashandel** [comment]
I was able to run it now. The processing and EDA portions are not that thorough, I have a hard time understanding if you have enough variables in your data to do some of the machine learning approaches we'll cover shortly and that I want to see in the project. Maybe your data is sufficient, I just can't tell from the information you are providing so far. But be prepared to potentially have to either add more data, create synthetic data to augment what you have, or switch to a different data source. Now that we are getting into the modeling part of the course, you should be able to assess if your data is suitable as is or not.

**Comment by anjoru** [comment]
Hi Dr. Handel,
Thank you for the feedback. As I am sure you can tell, I struggled with
part 2 of the project. Mainly because I did not allow myself enough time to
complete it. One of my major flaws is the lack of attention to detail, so
creating reproducible analysis is a huge challenge. I appreciate
your generous score. I have been working on improving it this week, but did
not think it was fair to push it to Github given that the deadline for
submission had already passed.

I am also looking for more data. For the actual project, that I will begin
this summer, I will have more than ten years of mosquito and virus data in
Massachusetts and will be adding more environmental data as well. I am
hoping to locate some raster spatial data that represents land cover, for
example.

Best, Andrew
